name: phpcstd

on: [push]

jobs:
  phpcstd:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
            ubuntu-latest,
            # windows-latest,
        ]
        php: [
            # 7.1,
            7.4,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: php-ast
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php }}-composer-

      - name: Remove easy-coding-standard on php 7.1
        run: composer remove --dev symplify/easy-coding-standard-prefixed
        if: ${{ matrix.php == 7.1 }}

      - name: Install dependencies
        run: composer install

      - name: Enable all tools
        run: sed -i -e 's/enabled = false/enabled = true/g' .phpcstd.dist.ini

      - name: Run phpcstd
        run: php bin/phpcstd --continue --ci

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Run tests
        run: vendor/bin/phpunit
